variables:
  AUDIT_AGENT_RULES_LIST:
      required: false
      type: array
      default:
        - echo-hello-1
        - echo-hello-2
        - echo-hello-3
        - echo-hello-4
        - echo-hello-5
        - echo-hello-6
        - echo-hello-7
        - echo-hello-8
        - echo-hello-9
        - echo-hello-10
        - env-user-password
